"""Job status determination for executions involving visualization nodes.

This module implements the failure isolation rules for jobs containing
visualization DAG nodes:

- Visualization failures NEVER change a calculation step's status from "success".
- If ANY calculation step fails → job status = "failed" (regardless of viz outcomes).
- If ALL calc steps succeed AND ≥1 viz node fails → job status = "completed_with_warnings".
- If ALL calc steps succeed AND ALL viz nodes succeed (or no viz nodes) → job status = "complete".
- Failed viz nodes produce a VisualizationSpec with status "failed" and error ≤500 chars.
- Each viz node produces exactly one VisualizationSpec regardless of other nodes' outcomes.
- Specs are returned ordered by topological position in the execution plan.
- Visualization nodes are subject to a 30-second execution timeout.

Requirements: 6.1, 6.2, 6.3, 6.4, 5.3, 5.4
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

from finflow_agent.execution.visualization.spec import VisualizationSpec
from finflow_agent.execution.visualization_runner import (
    VisualizationNode,
    _VISUALIZATION_TIMEOUT_SECONDS,
)


# ---------------------------------------------------------------------------
# Job Status Types
# ---------------------------------------------------------------------------

JobStatus = Literal["complete", "completed_with_warnings", "failed"]


# ---------------------------------------------------------------------------
# Result Container
# ---------------------------------------------------------------------------


@dataclass
class VisualizationJobResult:
    """Encapsulates the overall job result after visualization execution.

    Attributes:
        job_status: The resolved overall job status.
        visualization_specs: Ordered list of VisualizationSpecs (one per viz node).
        calc_step_statuses: Snapshot of calc step statuses (never modified by viz failures).
        warnings: Job-level warnings generated by the status handler.
    """

    job_status: JobStatus
    visualization_specs: list[VisualizationSpec]
    calc_step_statuses: dict[str, str]
    warnings: list[str]


# ---------------------------------------------------------------------------
# VisualizationJobStatusHandler
# ---------------------------------------------------------------------------


class VisualizationJobStatusHandler:
    """Determines overall job status given calc step results and viz node results.

    This handler enforces the failure isolation contract:
    - Viz failures NEVER propagate to calc step statuses (Req 6.1).
    - Job status follows a strict priority: calc failure > viz failure > all success.
    - Each viz node produces exactly one spec regardless of other nodes (Req 5.3).
    - Specs are returned in topological order (Req 5.4).

    Usage:
        handler = VisualizationJobStatusHandler()
        result = handler.determine_job_status(
            calc_step_results={"step1": {"status": "success", ...}},
            visualization_specs=specs_list,
            viz_nodes=nodes_list,
        )

    Requirements: 6.1, 6.2, 6.3, 6.4, 5.3, 5.4
    """

    @property
    def timeout_seconds(self) -> int:
        """The execution timeout for visualization nodes (30 seconds). Req 6.3."""
        return _VISUALIZATION_TIMEOUT_SECONDS

    def determine_job_status(
        self,
        calc_step_results: dict[str, dict[str, Any]],
        visualization_specs: list[VisualizationSpec],
        viz_nodes: list[VisualizationNode] | None = None,
    ) -> VisualizationJobResult:
        """Determine the overall job status based on calc and viz outcomes.

        Args:
            calc_step_results: Dictionary mapping calc step_id to result dicts.
                Each result must have at minimum a "status" key.
            visualization_specs: Ordered list of VisualizationSpecs produced
                by execute_visualization_nodes (already in topological order).
            viz_nodes: Optional list of VisualizationNodes for additional
                context (used to verify per-node isolation).

        Returns:
            VisualizationJobResult with resolved job_status, specs, and warnings.

        Requirements: 6.1, 6.2, 6.3, 6.4, 5.3, 5.4
        """
        # 1. Snapshot calc step statuses — these are NEVER modified by viz outcomes (Req 6.1).
        calc_statuses = {
            step_id: result.get("status", "unknown")
            for step_id, result in calc_step_results.items()
        }

        # 2. Check for any calc step failure (Req 6.4).
        any_calc_failed = any(
            status in ("failed", "partial")
            for status in calc_statuses.values()
        )

        # 3. Check for any viz node failure.
        any_viz_failed = any(
            spec.status == "failed" for spec in visualization_specs
        )

        # 4. Determine job status following the priority rules.
        warnings: list[str] = []

        if any_calc_failed:
            # Req 6.4: If ANY calc step fails → job status = "failed"
            # regardless of visualization outcomes.
            job_status: JobStatus = "failed"
        elif any_viz_failed:
            # Req 6.2: If ALL calc succeed AND ≥1 viz fails →
            # job status = "completed_with_warnings".
            job_status = "completed_with_warnings"
            failed_viz_count = sum(
                1 for spec in visualization_specs if spec.status == "failed"
            )
            warnings.append(
                f"{failed_viz_count} visualization(s) failed but all calculation "
                f"steps completed successfully."
            )
        else:
            # All calc succeeded and all viz succeeded (or no viz nodes).
            job_status = "complete"

        return VisualizationJobResult(
            job_status=job_status,
            visualization_specs=visualization_specs,
            calc_step_statuses=calc_statuses,
            warnings=warnings,
        )

    def verify_calc_status_isolation(
        self,
        calc_step_results_before: dict[str, str],
        calc_step_results_after: dict[str, dict[str, Any]],
    ) -> bool:
        """Verify that no calc step status was modified by visualization execution.

        Compares calc step statuses before and after visualization execution
        to ensure the failure isolation contract holds (Req 6.1).

        Args:
            calc_step_results_before: Mapping of step_id → status string
                captured BEFORE visualization execution.
            calc_step_results_after: The current calc step results dict
                (with full result envelopes).

        Returns:
            True if all calc step statuses are unchanged, False otherwise.
        """
        for step_id, before_status in calc_step_results_before.items():
            if step_id not in calc_step_results_after:
                return False
            after_status = calc_step_results_after[step_id].get("status")
            if after_status != before_status:
                return False
        return True

    @staticmethod
    def build_failed_viz_spec(
        *,
        operation_id: str,
        source_result_id: str,
        chart_type: str | None,
        error: str,
    ) -> VisualizationSpec:
        """Build a VisualizationSpec for a failed visualization node.

        Ensures the error message is capped at 500 characters (Req 6.3).

        Args:
            operation_id: The operation identifier.
            source_result_id: The source calculation step_id.
            chart_type: The requested chart type (or "auto" if None/empty).
            error: The error message (will be truncated to 500 chars).

        Returns:
            A VisualizationSpec with status "failed".
        """
        truncated_error = error[:500] if error else "Unknown visualization failure."
        return VisualizationSpec(
            operation_id=operation_id,
            source_result_id=source_result_id,
            status="failed",
            chart_type=chart_type or "auto",
            title="Visualization Failed",
            encoding={},
            data=[],
            error=truncated_error,
        )

    @staticmethod
    def build_timeout_viz_spec(
        *,
        operation_id: str,
        source_result_id: str,
        chart_type: str | None,
    ) -> VisualizationSpec:
        """Build a VisualizationSpec for a timed-out visualization node.

        The timeout is 30 seconds (Req 6.3).

        Args:
            operation_id: The operation identifier.
            source_result_id: The source calculation step_id.
            chart_type: The requested chart type.

        Returns:
            A VisualizationSpec with status "failed" and timeout error.
        """
        error_msg = (
            f"Visualization execution timed out after "
            f"{_VISUALIZATION_TIMEOUT_SECONDS} seconds."
        )
        return VisualizationSpec(
            operation_id=operation_id,
            source_result_id=source_result_id,
            status="failed",
            chart_type=chart_type or "auto",
            title="Visualization Failed",
            encoding={},
            data=[],
            error=error_msg,
        )
