"""add refresh_tokens table

Revision ID: 1859bbd362b3
Revises: 0002_admin_assignments
Create Date: 2026-05-17 14:36:27.151846
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '1859bbd362b3'
down_revision: Union[str, None] = '0002_admin_assignments'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.drop_index(op.f('idx_reviews_manager_reviewed'), table_name='reviews')
    op.drop_constraint(op.f('reviews_submission_id_key'), 'reviews', type_='unique')
    op.create_unique_constraint('uq_reviews_submission_id', 'reviews', ['submission_id'])
    op.drop_index(op.f('idx_submissions_parent'), table_name='submissions')
    op.drop_index(op.f('idx_submissions_status_uploaded'), table_name='submissions')
    op.drop_index(op.f('idx_submissions_user_uploaded'), table_name='submissions')
    op.drop_index(op.f('idx_transaction_rows_amount'), table_name='transaction_rows')
    op.drop_index(op.f('idx_transaction_rows_date'), table_name='transaction_rows')
    op.drop_index(op.f('idx_transaction_rows_submission'), table_name='transaction_rows')
    op.drop_index(op.f('idx_transaction_rows_transaction_id'), table_name='transaction_rows')
    op.drop_index(op.f('idx_users_manager_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_manager_id'), 'users', ['manager_id'], unique=False)
    op.create_index(op.f('idx_transaction_rows_transaction_id'), 'transaction_rows', ['transaction_id'], unique=False)
    op.create_index(op.f('idx_transaction_rows_submission'), 'transaction_rows', ['submission_id'], unique=False)
    op.create_index(op.f('idx_transaction_rows_date'), 'transaction_rows', ['transaction_date'], unique=False)
    op.create_index(op.f('idx_transaction_rows_amount'), 'transaction_rows', ['amount'], unique=False)
    op.create_index(op.f('idx_submissions_user_uploaded'), 'submissions', ['user_id', sa.literal_column('uploaded_at DESC')], unique=False)
    op.create_index(op.f('idx_submissions_status_uploaded'), 'submissions', ['review_status', sa.literal_column('uploaded_at DESC')], unique=False)
    op.create_index(op.f('idx_submissions_parent'), 'submissions', ['parent_submission_id'], unique=False)
    op.drop_constraint('uq_reviews_submission_id', 'reviews', type_='unique')
    op.create_unique_constraint(op.f('reviews_submission_id_key'), 'reviews', ['submission_id'])
    op.create_index(op.f('idx_reviews_manager_reviewed'), 'reviews', ['manager_id', sa.literal_column('reviewed_at DESC')], unique=False)
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
